---
# tasks file for ansible-role-shell
- name: Ensure ~/.shell exists
  file:
    path: ~/.shell
    state: directory

- name: Clone Tmux TPM
  git:
    clone: true
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Download kubectl aliases
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
    dest: ~/.shell/kubectl_aliases

- name: Download fzf
  git:
    clone: true
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf

- name: Install fzf
  command: ./install
  args:
    chdir: ~/.fzf

- name: Install fzf-tab
  git:
    clone: true
    repo: https://github.com/Aloxaf/fzf-tab
    dest: ~/.shell/fzf-tab

- name: Install forgit
  git:
    clone: true
    repo: https://github.com/wfxr/forgit.git
    dest: ~/.shell/forgit

- name: Install fzf-autosuggestions
  git:
    clone: true
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.shell/zsh-autosuggestions

- name: Install Fast Syntax Highlighting
  git:
    clone: true
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting
    dest: ~/.shell/fast-syntax-Highlighting

- name: Install zsh-history-substring-search
  git:
    clone: true
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: ~/.shell/zsh-history-substring-search

- name: Install zsh-completions
  git:
    clone: true
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.shell/zsh-completions

- name: Install bash-my-aws
  git:
    clone: true
    repo: https://github.com/bash-my-aws/bash-my-aws.git
    dest: ~/.bash-my-aws # cannot be "installed" in other path

- name: Install powerlevel10k
  git:
    clone: true
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.shell/powerlevel10k

- name: Clone NeoVim config
  git:
    clone: true
    repo: https://github.com/floatingman/neovim.git
    dest: ~/.config/nvim
